<?php 
/**
 * SiteClue
 * @category   SiteClue
 * @package    SiteClue_BackInStockDate
 * @copyright  Copyright (c) 2014-2015 SiteClue. (http://www.siteclue.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$_product = $this->getProduct();

?>
<?php if (($_product->getBackStockDate() != NULL) && (!$_product->isAvailable())) { echo '<p class="availability out-of-stock">Expected In Stock On: <span>' .  date("M-d-Y", strtotime($_product->getBackStockDate())).'</span></p>';} ?>